name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: make gcc g++ bison flex python3 libpython3-dev emscripten
        version: 1.0
    - name: Build
      run: make install
      env:
        INSTALL_PREFIX: ${{github.workspace}}/out 

    - name: Package
      run: tar -czvf check-shieve.tgz out --transform s/out/check-shieve/
    - uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: ${{github.workspace}}/check-shieve.tgz 

  release:
      permissions:
        contents: write
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - uses: actions/download-artifact@v5
          with:
            name: build-output
        - name: Release
          uses: softprops/action-gh-release@v2
          if: github.ref_type == 'tag'
          with:
            files: check-shieve.tgz 