name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt install -y make gcc g++ bison flex python3 libpython3-dev emscripten
      
    - name: Build
      run: make install
      env:
        INSTALL_DIR: "${{github.workspace}}/out"

    - uses: actions/upload-artifact@v4
      with:
        name: check-sieve
        path: ${{github.workspace}}/out
